import bcrypt from 'bcrypt'
const data = {
  users: [
    {
      name: 'Hamza',
      email: 'Hamza@gmail.com',
      password: bcrypt.hashSync('hamza323', 10),
      isAdmin: true,
    },
    {
      name: 'Hamza',
      email: 'Hamzahuss@gmail.com',
      password: bcrypt.hashSync('hamza323', 10),
      isAdmin: false,
    },
  ],

  products: [
    {
      id: 1,
      name: 'Free Shirt',
      slug: 'freeshirt',
      category: 'Shirts',
      image:
        'A13usaonutL._CLa_2140,2000_51dfLOXvrmL.png_0,0,2140,2000+0.0,0.0,2140.0,2000.0_AC_UY1000_.jpeg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
      isFeatured: true,
      banner:
        'A13usaonutL._CLa_2140,2000_51dfLOXvrmL.png_0,0,2140,2000+0.0,0.0,2140.0,2000.0_AC_UY1000_.jpeg',
    },
    {
      id: 2,
      name: 'Fit Shirt',
      slug: 'fitshirt',
      category: 'Shirts',
      image:
        'png-transparent-t-shirt-adidas-stan-smith-adidas-originals-trefoil-adidas-t-shirt-tshirt-white-logo.png',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
      isFeatured: true,
      banner:
        '/png-transparent-t-shirt-adidas-stan-smith-adidas-originals-trefoil-adidas-t-shirt-tshirt-white-logo.png',
    },
    {
      id: 3,
      name: 'Slim Shirt',
      slug: 'slimshirt',
      category: 'Shirts',
      image: '100148530617000_0_1682505954867.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      id: 4,
      name: 'Golf Pants',
      slug: 'golfpants',
      category: 'Pants',
      image: 'GFGPAD04-1-1000x1000.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Smart looking pants',
      banner: 'GFGPAD04-1-1000x1000.jpg',
      isFeatured: true,
    },
    {
      id: 5,
      name: 'Fit Pants',
      slug: 'fitpants',
      category: 'Pants',
      image: 'GFGPAD04-1-1000x1000.jpg',
      price: 95,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular pants',
      banner: 'GFGPAD04-1-1000x1000.jpg',
      isFeatured: true,
    },
    {
      id: 6,
      name: 'Classic Pants',
      slug: 'classicpants',
      category: 'Pants',
      image: 'GFGPAD04-1-1000x1000.jpg',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
      banner: 'GFGPAD04-1-1000x1000.jpg',
      isFeatured: true,
    },
  ],
}

export default data
